'use strict';
const V='0.2.3',K='projectHubSupabaseConfigV1',D='javidei',q=s=>document.querySelector(s);
const S={cfg:JSON.parse(localStorage.getItem(K)||'{}'),db:null,session:null,projects:[],tasks:[],f:{q:'',source:'all',status:'all',sort:'updated-desc'}};
S.cfg={githubOwner:S.cfg.githubOwner||D,supabaseUrl:S.cfg.supabaseUrl||'',supabaseAnonKey:S.cfg.supabaseAnonKey||''};
const E={badge:q('#connection-badge'),setup:q('#setup-card'),auth:q('#auth-card'),logout:q('#logout-button'),sync:q('#sync-github'),newP:q('#new-project'),newT:q('#new-task'),grid:q('#project-grid'),tasks:q('#task-list'),emptyP:q('#empty-projects'),emptyT:q('#empty-tasks'),count:q('#project-count'),owner:q('#github-owner-label'),toast:q('#toast'),settings:q('#settings-dialog'),project:q('#project-dialog'),task:q('#task-dialog')};
let tt;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const url=v=>{try{const u=new URL(v);return/^https?:$/.test(u.protocol)?u.href:''}catch{return''}};
const date=v=>{if(!v)return'Sin fecha';const d=new Date(v);return isNaN(d)?'Sin fecha':new Intl.DateTimeFormat('es-ES',{day:'2-digit',month:'short',year:'numeric'}).format(d)};
const toast=(m,e=false)=>{clearTimeout(tt);E.toast.textContent=m;E.toast.classList.toggle('is-error',e);E.toast.classList.add('is-visible');tt=setTimeout(()=>E.toast.classList.remove('is-visible'),5000)};
const publicKeyOk=k=>/^sb_publishable_[A-Za-z0-9_-]{20,}$/.test(k)||(/^eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+$/.test(k));
const configured=()=>/^https:\/\/.+\.supabase\.co\/?$/.test(S.cfg.supabaseUrl)&&publicKeyOk(S.cfg.supabaseAnonKey);
const weight=p=>({high:3,medium:2,low:1}[p]||0),sl=s=>({active:'Activo',paused:'Pausado',idea:'Idea',complete:'Terminado'}[s]||'Activo');
const schemaError=e=>{const m=`${e?.message||''} ${e?.details||''}`.toLowerCase();return e?.code==='42P01'||e?.code==='PGRST205'||(m.includes('project_hub_projects')&&m.includes('not'))||m.includes('schema cache')};
function explainDbError(e){if(schemaError(e))return 'Faltan las tablas de Project Hub en Supabase. Ejecuta supabase.sql en Supabase → SQL Editor y vuelve a intentarlo.';if(e?.code==='42501'||String(e?.message||'').toLowerCase().includes('row-level security'))return 'Supabase ha bloqueado la operación por permisos RLS. Comprueba que has iniciado sesión y que ejecutaste el SQL completo de Project Hub.';return `Error de Supabase: ${e?.message||'desconocido'}`}
function ui(){const ok=configured(),on=!!(ok&&S.session);E.owner.textContent=S.cfg.githubOwner||D;E.setup.hidden=ok;E.auth.hidden=!ok||on;E.logout.hidden=!on;E.sync.disabled=!ok;E.newP.disabled=!on;E.newT.disabled=!on;E.badge.classList.toggle('is-connected',on);E.badge.textContent=on?`Conectado · ${S.session.user.email||'Supabase'}`:ok?'Supabase configurado · falta iniciar sesión':'Sin configurar'}
function requestLogin(){if(!configured()){settings();toast('Primero configura Supabase.',true);return}E.auth.hidden=false;E.auth.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>q('#auth-email')?.focus(),350);toast('Para guardar la sincronización en Supabase, inicia sesión primero.',true)}
async function init(){S.db=null;S.session=null;S.projects=[];S.tasks=[];ui();render();if(!configured())return;if(!window.supabase?.createClient)return toast('No se pudo cargar la librería de Supabase.',true);try{S.db=window.supabase.createClient(S.cfg.supabaseUrl.replace(/\/$/,''),S.cfg.supabaseAnonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const r=await S.db.auth.getSession();if(r.error)throw r.error;S.session=r.data.session;ui();if(S.session)await load();S.db.auth.onAuthStateChange(async(_,s)=>{S.session=s;ui();if(s)await load();else{S.projects=[];S.tasks=[];render()}})}catch(e){toast(`Error de conexión: ${e.message}`,true)}}
async function load(){const[p,t]=await Promise.all([S.db.from('project_hub_projects').select('*').order('updated_at',{ascending:false}),S.db.from('project_hub_tasks').select('*').order('created_at',{ascending:false})]);if(p.error||t.error){toast(explainDbError(p.error||t.error),true);S.projects=[];S.tasks=[];render();return false}S.projects=p.data||[];S.tasks=t.data||[];render();return true}
async function gh(owner){let all=[];for(let page=1;page<=10;page++){const r=await fetch(`https://api.github.com/users/${encodeURIComponent(owner)}/repos?per_page=100&page=${page}&sort=updated&type=owner`,{headers:{Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'}});if(!r.ok){if(r.status===404)throw Error(`No existe el usuario "${owner}".`);throw Error(r.status===403?'GitHub ha aplicado temporalmente su límite de consultas. Vuelve a probar en unos minutos.':`GitHub respondió con error ${r.status}.`)}const a=await r.json();all.push(...a);if(a.length<100)break}return all}
async function sync(){if(!configured())return settings();if(!S.session)return requestLogin();E.sync.disabled=true;E.sync.textContent='Sincronizando…';try{const test=await S.db.from('project_hub_projects').select('id',{head:true,count:'exact'});if(test.error)throw test.error;const repos=await gh(S.cfg.githubOwner||D),map=new Map(S.projects.filter(x=>x.source==='github').map(x=>[x.source_key,x]));const rows=repos.map(r=>{const x=map.get(r.full_name),lang=r.language||'',tech=x?.tech?.length?x.tech:(lang?[lang]:[]);return{user_id:S.session.user.id,source:'github',source_key:r.full_name,github_id:r.id,github_owner:r.owner?.login||S.cfg.githubOwner,github_name:r.name,github_full_name:r.full_name,github_visibility:r.visibility||(r.private?'private':'public'),github_language:lang,github_default_branch:r.default_branch||'',github_archived:!!r.archived,github_fork:!!r.fork,github_stars:r.stargazers_count||0,github_open_issues:r.open_issues_count||0,github_topics:r.topics||[],github_pushed_at:r.pushed_at,github_synced_at:new Date().toISOString(),name:x?.name||r.name,description:x?.description||r.description||'',status:x?.status||(r.archived?'complete':'active'),priority:x?.priority||'medium',version:x?.version||'',category:x?.category||'GitHub',tech,live_url:x?.live_url||url(r.homepage||''),repo_url:r.html_url,notes:x?.notes||''}});if(rows.length){const z=await S.db.from('project_hub_projects').upsert(rows,{onConflict:'user_id,source,source_key'});if(z.error)throw z.error}await load();toast(`${repos.length} repositorios de GitHub sincronizados correctamente.`)}catch(e){toast(schemaError(e)?explainDbError(e):e?.code?explainDbError(e):`No se pudo sincronizar GitHub: ${e.message}`,true)}finally{E.sync.textContent='Sincronizar GitHub';E.sync.disabled=false;ui()}}
function list(){const s=S.f.q.toLowerCase().trim();return S.projects.filter(p=>(!s||[p.name,p.description,p.category,p.github_language,...(p.tech||[])].join(' ').toLowerCase().includes(s))&&(S.f.source==='all'||p.source===S.f.source)&&(S.f.status==='all'||p.status===S.f.status)).sort((a,b)=>S.f.sort==='name-asc'?a.name.localeCompare(b.name,'es'):S.f.sort==='priority-desc'?weight(b.priority)-weight(a.priority)||a.name.localeCompare(b.name,'es'):new Date(b.github_pushed_at||b.updated_at||0)-new Date(a.github_pushed_at||a.updated_at||0))}
function renderProjects(){const a=list();E.count.textContent=`${a.length} ${a.length===1?'proyecto':'proyectos'}`;E.emptyP.hidden=!!a.length;E.grid.innerHTML=a.map(p=>{const ru=url(p.repo_url),lu=url(p.live_url),tech=(p.tech||[]).slice(0,5),lang=p.github_language||tech[0]||'Sin definir';return`<article class="project-card" data-id="${esc(p.id)}"><div class="project-card__top"><div><span class="source-badge source-badge--${p.source}">${p.source==='github'?'GitHub':'Externo'}</span> <span class="status status--${esc(p.status)}">${sl(p.status)}</span></div><div class="project-card__menu"><button data-a="edit" title="Editar">✎</button><button data-a="del" title="Eliminar">×</button></div></div><h3>${esc(p.name)}</h3><p class="project-card__desc">${esc(p.description||'Sin descripción.')}</p><div class="project-card__details"><div><small>Versión</small><strong>${esc(p.version||'—')}</strong></div><div><small>Lenguaje</small><strong>${esc(lang)}</strong></div><div><small>Categoría</small><strong>${esc(p.category||'Sin categoría')}</strong></div><div><small>Actualizado</small><strong>${esc(date(p.github_pushed_at||p.updated_at))}</strong></div></div><div class="tech-list">${tech.map(x=>`<span>${esc(x)}</span>`).join('')}</div><div class="project-card__actions">${lu?`<a class="primary" href="${esc(lu)}" target="_blank" rel="noopener">Abrir web</a>`:''}${ru?`<a href="${esc(ru)}" target="_blank" rel="noopener">Repositorio</a>`:''}${!lu&&!ru?'<button data-a="edit">Completar datos</button>':''}</div></article>`}).join('')}
function renderTasks(){const a=[...S.tasks].sort((x,y)=>+x.done-+y.done||weight(y.priority)-weight(x.priority));E.emptyT.hidden=!!a.length;E.tasks.innerHTML=a.map(t=>{const p=S.projects.find(x=>x.id===t.project_id);return`<article class="task-card ${t.done?'is-done':''}" data-id="${esc(t.id)}"><input type="checkbox" data-a="toggle" ${t.done?'checked':''}><div><h3>${esc(t.title)}</h3><p>${esc(p?.name||'Proyecto eliminado')} · ${esc(t.priority)}${t.due_date?` · ${esc(date(t.due_date))}`:''}</p></div><button data-a="delTask">×</button></article>`}).join('')}
function render(){ui();q('#stat-total').textContent=S.projects.length;q('#stat-github').textContent=S.projects.filter(x=>x.source==='github').length;q('#stat-manual').textContent=S.projects.filter(x=>x.source==='manual').length;q('#stat-tasks').textContent=S.tasks.filter(x=>!x.done).length;renderProjects();renderTasks();q('#task-project').innerHTML=[...S.projects].sort((a,b)=>a.name.localeCompare(b.name,'es')).map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('')}
function settings(){q('#github-owner').value=S.cfg.githubOwner||D;q('#supabase-url').value=S.cfg.supabaseUrl;q('#supabase-anon-key').value=S.cfg.supabaseAnonKey;E.settings.showModal()}
function openProject(p){if(!S.session)return requestLogin();q('#project-dialog-title').textContent=p?'Editar proyecto':'Añadir proyecto externo';q('#project-id').value=p?.id||'';q('#project-name').value=p?.name||'';q('#project-version').value=p?.version||'';q('#project-status').value=p?.status||'active';q('#project-priority').value=p?.priority||'medium';q('#project-category').value=p?.category||'';q('#project-tech').value=(p?.tech||[]).join(', ');q('#project-description').value=p?.description||'';q('#project-live-url').value=p?.live_url||'';q('#project-repo-url').value=p?.repo_url||'';E.project.showModal()}
async function saveProject(e){e.preventDefault();const id=q('#project-id').value,x=S.projects.find(p=>p.id===id),row={user_id:S.session.user.id,source:x?.source||'manual',source_key:x?.source_key||crypto.randomUUID(),name:q('#project-name').value.trim(),description:q('#project-description').value.trim(),status:q('#project-status').value,priority:q('#project-priority').value,version:q('#project-version').value.trim(),category:q('#project-category').value.trim(),tech:q('#project-tech').value.split(',').map(x=>x.trim()).filter(Boolean),live_url:q('#project-live-url').value.trim(),repo_url:q('#project-repo-url').value.trim()};const r=id?await S.db.from('project_hub_projects').update(row).eq('id',id):await S.db.from('project_hub_projects').insert(row);if(r.error)return toast(explainDbError(r.error),true);E.project.close();q('#project-form').reset();await load();toast(id?'Proyecto actualizado.':'Proyecto externo añadido.')}
async function delProject(id){const p=S.projects.find(x=>x.id===id);if(!p||!confirm(`¿Eliminar "${p.name}" de Project Hub?`))return;const r=await S.db.from('project_hub_projects').delete().eq('id',id);if(r.error)return toast(explainDbError(r.error),true);await load();toast(p.source==='github'?'Se volverá a importar en la próxima sincronización.':'Proyecto eliminado.')}
async function saveTask(e){e.preventDefault();const r=await S.db.from('project_hub_tasks').insert({user_id:S.session.user.id,project_id:q('#task-project').value,title:q('#task-title').value.trim(),priority:q('#task-priority').value,due_date:q('#task-due-date').value||null});if(r.error)return toast(explainDbError(r.error),true);E.task.close();q('#task-form').reset();await load();toast('Tarea añadida.')}
async function taskAction(id,done,del=false){const r=del?await S.db.from('project_hub_tasks').delete().eq('id',id):await S.db.from('project_hub_tasks').update({done}).eq('id',id);if(r.error)toast(explainDbError(r.error),true);else await load()}
q('#open-settings').onclick=settings;q('#setup-now').onclick=settings;E.sync.onclick=sync;E.newP.onclick=()=>openProject();E.newT.onclick=()=>{if(!S.session)return requestLogin();if(!S.projects.length)return toast('Necesitas al menos un proyecto.',true);E.task.showModal()};
q('#settings-form').onsubmit=async e=>{e.preventDefault();const githubOwner=q('#github-owner').value.trim()||D,supabaseUrl=q('#supabase-url').value.trim(),supabaseAnonKey=q('#supabase-anon-key').value.trim();if(!/^https:\/\/.+\.supabase\.co\/?$/.test(supabaseUrl))return toast('La Project URL de Supabase no parece válida.',true);if(!publicKeyOk(supabaseAnonKey))return toast('Usa la Publishable key (sb_publishable_...) o la antigua anon key.',true);S.cfg={githubOwner,supabaseUrl,supabaseAnonKey};localStorage.setItem(K,JSON.stringify(S.cfg));E.settings.close();await init();toast('Configuración guardada. Si aún no has iniciado sesión, hazlo antes de sincronizar.')};
q('#project-form').onsubmit=saveProject;q('#task-form').onsubmit=saveTask;
q('#auth-form').onsubmit=async e=>{e.preventDefault();if(!S.db)return toast('Primero configura Supabase.',true);const r=await S.db.auth.signInWithPassword({email:q('#auth-email').value.trim(),password:q('#auth-password').value});toast(r.error?`No se pudo entrar: ${r.error.message}`:'Sesión iniciada. Ya puedes sincronizar GitHub.',!!r.error)};
q('#signup-button').onclick=async()=>{if(!S.db)return toast('Primero configura Supabase.',true);const email=q('#auth-email').value.trim(),password=q('#auth-password').value;if(!email||password.length<6)return toast('Email y contraseña de al menos 6 caracteres.',true);const r=await S.db.auth.signUp({email,password});toast(r.error?`No se pudo crear: ${r.error.message}`:r.data.session?'Cuenta creada. Ya puedes sincronizar.':'Cuenta creada. Revisa el correo de confirmación antes de entrar.',!!r.error)};
E.logout.onclick=()=>S.db?.auth.signOut();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>q(`#${b.dataset.close}`).close());
q('#search-input').oninput=e=>{S.f.q=e.target.value;renderProjects()};q('#source-filter').onchange=e=>{S.f.source=e.target.value;renderProjects()};q('#status-filter').onchange=e=>{S.f.status=e.target.value;renderProjects()};q('#sort-select').onchange=e=>{S.f.sort=e.target.value;renderProjects()};
E.grid.onclick=e=>{const b=e.target.closest('[data-a]'),c=e.target.closest('.project-card');if(!b||!c)return;const p=S.projects.find(x=>x.id===c.dataset.id);b.dataset.a==='edit'?openProject(p):delProject(c.dataset.id)};
E.tasks.onchange=e=>{const c=e.target.closest('.task-card');if(c&&e.target.dataset.a==='toggle')taskAction(c.dataset.id,e.target.checked)};
E.tasks.onclick=e=>{const c=e.target.closest('.task-card');if(c&&e.target.dataset.a==='delTask')taskAction(c.dataset.id,false,true)};
init();